### PR TITLE
Fixed branch param name in the jenkings notification url.

### PR DESCRIPTION
**Pull request by mobikop**

### CODE REVIEW

**Comment by Nathan-Smith** [comment]
:+1:

**Comment by mikesir87** [comment]
Gah! Nice catch. Not sure how this one slipped through.  Thanks!

**Comment by Nathan-Smith** [comment]
@mikesir87, When can we expect this released to the Marketplace?

**Comment by Nathan-Smith** [comment]
@mikesir87, any update on getting this released to the Marketplace?

**Comment by mikesir87** [comment]
@Nathan-Smith Sorry for the slow response. I hope to get it out in the next day or two.

**Comment by Nathan-Smith** [comment]
@mikesir87, can you update me on the status of the upcoming release please.

**Comment by mikesir87** [comment]
Yes. And I apologize (yet again).  I'll get it out this afternoon.  I was hoping to get another bug resolved before the next release, but it's taking longer than expected to nail down (may end up being an Atlassian issue).

**Comment by mikesir87** [comment]
It's been pushed to the Marketplace now.  You should see it show up shortly.

**Comment by Nathan-Smith** [comment]
Thank you very much! I appreciate it.

**Pull request merged**
